version: 2.0
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: make gen-report
    store_test_results:
          path: /

workflows:
  version: 2
  build_and_test:
    jobs:
      - build