version: 2.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mkdir test-results
      - run: docker build -t dla-test .
      - run: docker run -v ~/project/test-results:/usr/src/project/test-results dla-test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build